# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory_model.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15inventory_model.proto\x12\x0finventorySystem\"h\n\x04\x42ook\x12\x0c\n\x04isbn\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12%\n\x05genre\x18\x04 \x01(\x0e\x32\x16.inventorySystem.Genre\x12\x0c\n\x04year\x18\x05 \x01(\x05\"w\n\rInventoryItem\x12\x0e\n\x06number\x18\x01 \x01(\x05\x12%\n\x04\x62ook\x18\x02 \x01(\x0b\x32\x15.inventorySystem.BookH\x00\x12\'\n\x06Status\x18\x03 \x01(\x0e\x32\x17.inventorySystem.StatusB\x06\n\x04item*N\n\x05Genre\x12\r\n\tADVENTURE\x10\x00\x12\r\n\tBIOGRAPHY\x10\x01\x12\n\n\x06SPORTS\x10\x02\x12\x0e\n\nTECHNOLOGY\x10\x03\x12\x0b\n\x07MYSTERY\x10\x04*\"\n\x06Status\x12\r\n\tAVAILABLE\x10\x00\x12\t\n\x05TOKEN\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_model_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENRE._serialized_start=269
  _GENRE._serialized_end=347
  _STATUS._serialized_start=349
  _STATUS._serialized_end=383
  _BOOK._serialized_start=42
  _BOOK._serialized_end=146
  _INVENTORYITEM._serialized_start=148
  _INVENTORYITEM._serialized_end=267
# @@protoc_insertion_point(module_scope)
